export class Kontrak{
     id: string
     nomor: string;
     nama: string;
     jenisSGU: string;
     tglRealisasi: Date;
     tgl_realisasi: Date;
     bpkb: boolean;
     polis: boolean;
     cn: boolean;
     spHak: boolean;
     bast: boolean;
     faktur: boolean;
     PO: boolean;
     SPbpkb: boolean;
     jadwalSGU: boolean;
     memoHak: boolean;
     buktiPenerimaan: boolean;
     SPAsuransi: boolean;
     suratKuasa: boolean;
     spAnggaran: boolean;
     persetujuanPasangan: boolean;
     persetujuanKomisaris: boolean;
     buktiPeneyrahan: boolean;
     SPtanpaRUPS: boolean;
     perjanjianJualBeli: boolean;
     pelepasanHak: boolean;
     penyerahanBPKB: boolean;
     jaminan: boolean;
     SPDirektur: boolean;
     beritaRUPS: boolean;
     SKRekening: boolean;
     pelunasan: boolean;
     persetujuanSGU: boolean;
     rekeningBCA: boolean;
     barangModal: boolean;
     DP: boolean;
     buktiBayar: boolean;
     FotoGesekan: boolean;
     KTPKonsumenPasangan: boolean;
     aktaNikah: boolean;
     K3: boolean;
     kartuKeluarga: boolean;
     NPWP: boolean;
     resumePT: boolean;
     TDP: boolean;
     SIUP: boolean;
     ktpPengurus: boolean;
     domisiliPT: boolean;
     dokumenLain: boolean;
     borrow: boolean;
     keterangan: String;
     keterangan2: String;
     sp_Bpkb:boolean;
     jadwal_SGU:boolean;
    po2:boolean;
    sp_asuransi:boolean;
    spNonRUPS:boolean;
    sp_Direktur:boolean;
    sk_Rekening:boolean;
    dp2:boolean;
    ktpKonsumenPasang:boolean;
    npwp2:boolean;
    tdp2:boolean;
    siup2:boolean;
    k_3:boolean;
    fotoGesek:boolean;
    jumlahBPKB:number;
    nomorBPKB:String;
    userData:String;
}